# Generated by Django 2.0.1 on 2018-02-21 04:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='liker_set',
            field=models.ManyToManyField(related_name='liked_article_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='liker_set',
            field=models.ManyToManyField(related_name='liked_comment_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
